services:
  - name: nodejs-app
    image: node:21.1.0
    command: ["npm", "start"]
    ports:
      - name: http
        port: 3001
        protocol: HTTP
    env:
      - name: NODE_ENV
        value: production
